public class Animation
{
private static final String RED = "\u001B[31m";
private static final String WHITE = "\u001B[37m";
public static void clearScreen(){
  System.out.print("\033[H\033[2J");
  System.out.flush();
}



/** animation for when user at b1 shooting at b1 and when comp at b1 shooting at b1
*/
public static void oneoneoneone() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println(" | |");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
    System.out.println("  |");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
}

/**animation for when user at b1 shooting at b2 and when comp at b1 shooting at b1
*/
public static void oneonetwoone() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println("     /");
    System.out.println("-----   -----   ");
    System.out.println("|   |   |   |   ");
    System.out.println("-----   -----  ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----   ");
    System.out.println("| 1 |   | 2 |   ");
    System.out.println("-----   -----   ");
    System.out.println();
    System.out.println("  |    /");
    System.out.println();
    System.out.println("-----   -----   ");
    System.out.println("|   |   |   |   ");
    System.out.println("-----   -----   ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   -----  ");
    System.out.println("         /");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   ----- ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   |  ");
    System.out.println("-----   -----  ");
    System.out.println("   /");
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
}

/**animation for when user at b1 shooting at b1 and when comp at b1 shooting at b2
*/
public static void oneoneonetwo() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("     \\");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("  |    \\");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println("        \\");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
    System.out.println("   \\");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");

}

/**animation for when user at b1 shooting at b2 and when comp at b1 *shooting at b2
*/
public static void oneonetwotwo() throws InterruptedException
{
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("     \\");
    System.out.println();
    System.out.println("      /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("      /\\");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("        /");
    System.out.println();
    System.out.println("        \\");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
}

/** animation for when user at b2 shooting at b1 and when comp at b1 *shooting at b1
*/
public static void twooneoneone() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("  |");
    System.out.println();
    System.out.println("        \\");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println("  |   \\");
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("   \\");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
}

/**animation for when user at b2 shooting at b2 and when comp at b1 *shooting at b1
*/
public static void twoonetwoone() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("  |");
    System.out.println();
    System.out.println("          | ");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println("  |       |");
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("  |");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
}

/**animation for when user at b2 shooting at b1 and when comp at b1 *shooting at b2
*/
public static void twooneonetwo() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("    \\");
    System.out.println();
    System.out.println("        \\");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println("     \\\\");
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("   \\");
    System.out.println();
    System.out.println("      \\");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println("           O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          \\");
    System.out.println(Animation.RED + "           X" + Animation.WHITE);
}

/**animation for when user at b2 shooting at b2 and when comp at b1 *shooting at b2
*/
public static void twoonetwotwo() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("    \\");
    System.out.println();
    System.out.println("           |");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println("      \\   |");
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println();
    System.out.println("      \\");
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("  O");
    System.out.println("   \\");
    System.out.println("-----   -----");
    System.out.println("| 1 |   | 2 |");
    System.out.println("-----   -----");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----");
    System.out.println("|   |   |   |");
    System.out.println("-----   -----");
    System.out.println("           |");
    System.out.println(Animation.RED + "           X" + Animation.WHITE);
}

/**animation for when user at b2 shooting at b1 and when comp at b2 *shooting at b1
*/
public static void twotwooneone() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("      /");
    System.out.println();
    System.out.println("      \\");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("      /\\");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("    \\");
    System.out.println();
    System.out.println("   /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");

}

/**animation for when user at b2 shooting at b2 and when comp at b2 shooting at b1
*/
public static void twotwotwoone() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("      /");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("     /    |");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("   /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "          X" + Animation.WHITE);
    System.out.println("         /");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
}

/**animation for when user at b2 shooting at b1 and when comp at b2 *shooting at b2
*/
public static void twotwoonetwo() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("        \\");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("     \\    |");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("    \\");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("         \\");
    System.out.println(Animation.RED + "          X" + Animation.WHITE);
}

/**animation for when user at b2 shooting at b2 and when comp at b2 *shooting at b2
*/
public static void twotwotwotwo() throws InterruptedException 
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("         ||");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println("          O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "          X" + Animation.WHITE);
    System.out.println("          |");
    System.out.println("-----   ----- ");
    System.out.println("| 1 |   | 2 | ");
    System.out.println("-----   ----- ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("          |");
    System.out.println(Animation.RED + "          X" + Animation.WHITE);

}

/**animation for when user at b1 shooting at b1 and when comp at b2 *shooting at b1 
*/
public static void onetwooneone() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("       /");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("  |   /");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println("    /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
}

/** animation for when user at b1 shooting at b1 and when comp at b2 *shooting at b2 
*/
public static void onetwoonetwo() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("  |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("  |       |");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("  |");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("  |");
    System.out.println("  O");
}

/**animation for when user at b1 shooting at b2 and when comp at b2 *shooting at b1 
*/
public static void onetwotwoone() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("       /");
    System.out.println();
    System.out.println("    /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("     //");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("       /");
    System.out.println();
    System.out.println("    /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "          X" + Animation.WHITE);
    System.out.println("         /");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println(Animation.RED + "  X" + Animation.WHITE);
}

/**animation for when user at b1 shooting at b2 and when comp at b2 *shooting at b2
*/
public static void onetwotwotwo() throws InterruptedException
{
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("          |");
    System.out.println();
    System.out.println("    /");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println("     /    |");
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println("          O");
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println("      /");
    System.out.println();
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
    Thread.sleep(500);
    clearScreen();
    System.out.println();
    System.out.println(Animation.RED + "          X" + Animation.WHITE);
    System.out.println("          |");
    System.out.println("-----   -----  ");
    System.out.println("| 1 |   | 2 |  ");
    System.out.println("-----   -----  ");
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println("-----   -----  ");
    System.out.println("|   |   |   | ");
    System.out.println("-----   ----- ");
    System.out.println("   /");
    System.out.println("  O");
}


}